spring:
  application:
    name: financetrack

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    init:
      admin:
        username: ${DATASOURCE_ADMIN_USERNAME:admin}
        password: ${DATASOURCE_ADMIN_PASSWORD:nimda}

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080
  shutdown: graceful

  servlet:
    context-path: /api/v1

jwt:
  secret: Kc_eXseIh7h5Lc$>KTHPP/U)/qZ-~<f?9SE*u~lW
  issuer: financetrack
  expiration: 7776000
