spring:
  application:
    name: financetrack
  datasource:
    init:
      admin:
        username: ${DATASOURCE_ADMIN_USERNAME:admin}
        password: ${DATASOURCE_ADMIN_PASSWORD:nimda}

jwt:
  secret: Kc_eXseIh7h5Lc$>KTHPP/U)/qZ-~<f?9SE*u~lW
  issuer: financetrack
  expiration: 7776000
